### PR TITLE
grunt-sass/node-sass bump

### PR DESCRIPTION
**Pull request by lsh-0**
~bumps grunt-sass to v2 so it's node-sass dependency can build with newer versions of libsass.~

~I think?~

fixes the versions of dependencies installed so only newer *patch* versions are installed, rather than newer *minor* versions, with the exception of `fullcalendar` whose newer minor version appears to fix some bugs.

This may cause older versions of libraries to be installed on `elife-dashboard--prod`! It passes tests so it should be ok, but who knows? It's been four years since a js dev last touched it.

### CODE REVIEW

**Comment by lsh-0** [comment]
supergreen

**Comment by lsh-0** [comment]
@NuclearRedeye , could I get you to review my changes please? I think what I've done is safer for this js code that is otherwise unmaintained.

**Review by NuclearRedeye — APPROVED** [review]
Yup,, changes seem fine to me

**Comment by lsh-0** [comment]
I'll merge Monday so I'm around to fix any problems in prod

**Pull request merged**
