### PR TITLE
bumps version of Django in (unused) dashboard_2

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
build had an instance of nginx that needed restarting as it was started before the old certificate had been replaced. this is a `todo` for the formula

**Comment by giorgiosironi** [comment]
Why do PRs here go to `end2end`? :scream_cat:

**Comment by giorgiosironi** [comment]
Ah it's a merge from `develop` to `master`. The build still failed.

**Comment by giorgiosironi** [comment]
I will make it green but then close it as the merge will be performed by Jenkins.

**Comment by lsh-0** [comment]
I can see the change in `master`, cheers @giorgiosironi

**Pull request closed without merging**
