### PR TITLE
Change logo and favicon

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
Have added these but needs testing before putting live. @giorgiosironi has said this is hard to run locally.

**Comment by giorgiosironi** [comment]
The build turns on https://ci--ppp-dash.elifesciences.org/current (same credentials as elsewhere) and I have now locked it in https://alfred.elifesciences.org/lockable-resources/ (admin link) so that it stays on. It looks a bit broken but I have to check whether that is an existing problem.

**Comment by giorgiosironi** [comment]
https://ci--ppp-dash.elifesciences.org/current up and locked again. Logo shows. Favicon shows.

**Comment by giorgiosironi** [comment]
Let me know if you are satisfied and want to merge, I'll unlock the pipeline.

**Pull request merged**
