### PR TITLE
Smoke test article scheduler

### PR DESCRIPTION
**Pull request by giorgiosironi**
Removes test for dashboard_2 which has never been used, adds one for elife-article-scheduler

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Of course this fails, because as it is the formula doesn't work for `elife-article-scheduler`.

**Comment by lsh-0** [comment]
* formula is now green.
* changed base of this PR to `master` (where development is happening :|)
* kicking build

**Comment by lsh-0** [comment]
404 on the smoke tests. investigating

**Comment by lsh-0** [comment]
turns out the article-scheduler doesn't actually have any api endpoints that can be GETed without passing some parameters. I'll look into a `/ping` endpoint for this smoketest

the smoketest being replaced here is still viable, it's just not for the article-scheduler:

```
$ curl -I https://$(hostname):8081/api/current
++ hostname
+ curl -I https://ci--ppp-dash.elifesciences.org:8081/api/current
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 18 Mar 2019 02:17:21 GMT
Content-Type: application/json
Content-Length: 53
Connection: keep-alive
Allow: GET, HEAD, OPTIONS
X-Frame-Options: SAMEORIGIN
Vary: Accept
```

I'll re-instate it and add one for the scheduler as well

**Comment by lsh-0** [comment]
adds a /ping endpoint https://github.com/elifesciences/elife-article-scheduler/pull/9

**Comment by lsh-0** [comment]
all green, merging

**Comment by lsh-0** [comment]
> changed base of this PR to master (where development is happening :|)

I was thinking of `elife-article-scheduler`, my mistake

**Pull request merged**
