### PR TITLE
fix: update elife-dashboard to support node.js version 16

### PR DESCRIPTION
**Pull request by NuclearRedeye**

### CODE REVIEW

**Comment by NuclearRedeye** [comment]
@lsh-0 An initial stab at getting the dashboard working with the newer version of node. I've done some really limited testing of the frontend locally and it _seems_ ok to me. Not sure if there is a means by which you'd like to test this branch further at all to validate that overall the project is OK? for example in end2end if that is possible?

**Comment by NuclearRedeye** [comment]
My guess is that the CI failure is because that node is not currently using Node v16 which is now the minimum requirement.

**Comment by NuclearRedeye** [comment]
> My guess is that the CI failure is because that node is not currently using Node v16 which is now the minimum requirement.

Just tested these changes locally, they work with Node.js v10 but with Node.js v8 I can replicate the issue that CI is seeing, hence I'm confident that the failure is caused by the version of node on the Jenkins worker.

**Comment by lsh-0** [comment]
> Just tested these changes locally, they work with Node.js v10 but with Node.js v8 I can replicate the issue that CI is seeing, hence I'm confident that the failure is caused by the version of node on the Jenkins worker.

Ubuntu 18.04 has nodejs v6 installed, not v8. Ubuntu 20.04 will have v16 installed.

It's a massive jump and I wouldn't be surprised if it's impossible to have a compatible set of dependencies that works on v6 *and* v16.

I can see the `install.sh` script in elife-dashboard is trying to run `npm install` as well, which is probably exacerbating things.

If it can't be done I'll containerise it and we can stay on nodejs 6 indefinitely.

**Comment by NuclearRedeye** [comment]
> If it can't be done I'll containerise it and we can stay on nodejs 6 indefinitely.

I think it can be, just merge and deployment will be a little fiddly and will need coordinating as at some stage something will be in a broken state as we transition from one state to another. Packaging it up into a container though would be a good idea although it might be more effort than you want to undertake at the moment.
I had a crack at it not that long ago, but was having some issues getting flask to serve the dashboard. I'll see if I can find the branch and at least push it so that it's public and somebody else can pick it up if they desire.

**Comment by lsh-0** [comment]
> I'll see if I can find the branch and at least push it so that it's public and somebody else can pick it up if they desire.

That'd be good, actually. Flask/Django/Python apps+uwsgi+web server can definitely be fiddly.

**Comment by lsh-0** [comment]
hmmm - elife-dashboard appears to have just built fine on nodejs 16 using this PR

I'll take a closer look at these build errors tomorrow.

**Comment by NuclearRedeye** [comment]
@lsh-0 In slack you said this was failing in 18.04, specifically did you mean failing in 18.04 with Node.js v16? Or failing in 18.04 with Node.js v6? If the later, that's expected. I don't think there is any route to making a single PR compatible with both.

**Comment by lsh-0** [comment]
> I haven't tested nodejs16+18.04 but I suspect that will work.

yes, it looks like it's working. I'm going to test the upgrade path from nodejs 6 to nodejs 16 and if that works then I'll get elife-dashboard upgraded Friday.

**Comment by lsh-0** [comment]
- [ ] switch formula to nodejs16: https://github.com/elifesciences/elife-dashboard-formula/pull/30
- [x] switch builder-config to nodejs16: https://github.com/elifesciences/builder-configuration/pull/257
- [ ] make this PR green
- [ ] merge

**Comment by lsh-0** [comment]
well, on the formula and dependencies side everything is working but the project tests are no longer passing. I can replicate this in a vagrant machine.

we have two errors that look identical:

```
Warning: Command failed: ls ./assets/test/*.html | xargs -I % ./node_modules/.bin/mocha-headless-chrome -e /usr/bin/chromium-browser -a no-sandbox -f %
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long
    at /srv/elife-dashboard/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/srv/elife-dashboard/node_modules/puppeteer/lib/Connection.js:182:12)
    at JSHandle.jsonValue (/srv/elife-dashboard/node_modules/puppeteer/lib/JSHandle.js:105:43)
    at JSHandle.<anonymous> (/srv/elife-dashboard/node_modules/puppeteer/lib/helper.js:112:23)
    at /srv/elife-dashboard/node_modules/mocha-headless-chrome/lib/runner.js:131:33
    at Array.map (<anonymous>)
    at Page.handleConsole (/srv/elife-dashboard/node_modules/mocha-headless-chrome/lib/runner.js:131:22)
    at Page.emit (node:events:526:28)
    at Page._addConsoleMessage (/srv/elife-dashboard/node_modules/puppeteer/lib/Page.js:628:10)
  -- ASYNC --
    at JSHandle.<anonymous> (/srv/elife-dashboard/node_modules/puppeteer/lib/helper.js:111:15)
    at /srv/elife-dashboard/node_modules/mocha-headless-chrome/lib/runner.js:131:33
    at Array.map (<anonymous>)
    at Page.handleConsole (/srv/elife-dashboard/node_modules/mocha-headless-chrome/lib/runner.js:131:22)
    at Page.emit (node:events:526:28)
    at Page._addConsoleMessage (/srv/elife-dashboard/node_modules/puppeteer/lib/Page.js:628:10)
    at Page._onConsoleAPI (/srv/elife-dashboard/node_modules/puppeteer/lib/Page.js:550:10)
    at CDPSession.<anonymous> (/srv/elife-dashboard/node_modules/puppeteer/lib/Page.js:119:57)
    at CDPSession.emit (node:events:526:28)
    at CDPSession._onMessage (/srv/elife-dashboard/node_modules/puppeteer/lib/Connection.js:200:12)
 Use --force to continue.

Aborted due to warnings.
```

It says 'Aborted due to warnings.' but the message actually says 'error'.

Taking it's advice, I added `--force` to the end of the project tests and they now pass locally. Pushing the change up ...

**Comment by lsh-0** [comment]
I'm going to merge this because the elife-dashboard instances are in a weird/broken state without a nodejs16-capable elife-dashboard project, but it would be good to figure out what it's complaining about and remove that `--force` flag.

**Comment by lsh-0** [comment]
all other testing and deployment went fine

**Pull request merged**
