### PR TITLE
Frontend tests: Current

### PR DESCRIPTION
**Pull request by apricot13**
Tests for the current page.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Are some of these files being generated? Not the first time there's a huge diff, just wondering.

**Comment by giorgiosironi** [comment]
These tests are not run by Alfred at the moment, and http://jira.elifesciences.org:8080/browse/ELPP-1188 is for solving that. Can you answer the questions there so that I can add the front end test execution step?

**Comment by apricot13** [comment]
@giorgiosironi 4 of them are autogenerated yes.

**Comment by giorgiosironi** [comment]
@apricot13 what generates them? One popular pattern is to ignore them and have the build process generate them, to avoid the noise in commits.

**Comment by apricot13** [comment]
@giorgiosironi the reason I went with the 'commit all the things' approach was to avoid issues with npm since I was still adding features/changing versions all the time which would have meant the backend guys might not have had the latest templates.

Now that things aren't changing as much I'm more than happy to un-version the built files - do you want me to create a ticket for that?

**Comment by giorgiosironi** [comment]
Not my decision to change the approach, @davidcmoulton should have a say on this :)

**Comment by davidcmoulton** [comment]
I favour removing autogenerated artefacts from version control.

**Comment by apricot13** [comment]
Closing in favour of https://github.com/elifesciences/elife-dashboard/pull/6

**Pull request closed without merging**
