### PR TITLE
Add smoke test

### PR DESCRIPTION
**Pull request by seanwiseman**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The smoke test failed in `ci`, but apart from that it seems this URL is not covered by authentication. That is a prerequisite to sort out, we can allow local requests to be whitelisted but I would expect this port to refuse everything requested without authentication like in https://github.com/elifesciences/elife-dashboard-formula/blob/master/salt/elife-dashboard/config/etc-nginx-sitesenabled-app.conf#L33-L34

**Comment by seanwiseman** [comment]
Once I can actually add new tables to the prod DB (Django auth, sessions etc..) I can use the prefered authentication methods.

**Comment by giorgiosironi** [comment]
Uhm still red?

**Comment by seanwiseman** [comment]
This is now a 401 auth failure, which is expected with the current configuration as we are not passing it the auth details required by nginx.

What strategy should be used to resolve this? do we have another smoke test example where nginx authentication is in play?

**Comment by giorgiosironi** [comment]
Yes, my standard solution is to allow all local requests so that the smoke tests can skip authentication:
https://github.com/elifesciences/journal-formula/blob/master/salt/journal/config/etc-nginx-sites-available-journal.conf#L117-L119

**Comment by seanwiseman** [comment]
Latest failure was due to the db being dropped by the original test suite and there not being a db present when the smoke tests run. [This PR](https://github.com/elifesciences/elife-dashboard/pull/21) should resolve this.

**Comment by giorgiosironi** [comment]
There are other PRs running simultaneously to the one fixing the database teardown, so after that one is merged a new highstate and recreation of the tables is needed as a one-off.

**Comment by seanwiseman** [comment]
Now green.

**Comment by giorgiosironi** [comment]
It is a bit weird that we were seeing so many changes, since most of them (the database cleanup) were already in `develop`.

**Pull request merged**
