### PR TITLE
disables smoketest for dashboard2:8081 and adds one for dashboard:443

### PR DESCRIPTION
**Pull request by lsh-0**
dashboard2 is not supported

### CODE REVIEW

**Comment by lsh-0** [comment]
I think this also means that the smoketest for the regular dashboard hasn't been running

**Comment by lsh-0** [comment]
`Referenced state service: uwsgi-elife-dashboard does not exist`

nuts. this is me merging the builder-private update to the newrelic_python stuff. I'll revert, kick, merge, restore, kick 1804 build

**Comment by lsh-0** [comment]
```
[2019-04-05T05:32:32.849Z] [54.196.183.26] out: ++ curl --write-out '%{http_code}' --silent --output /dev/null https://ci--ppp-dash.elifesciences.org/api/current
[2019-04-05T05:32:32.849Z] [54.196.183.26] out: + '[' 401 == 200 ']'
```

*really* frustrating but not unexpected. It's also a perfectly sensible response. No idea how to inject credentials so we have `https://$user:$pass@ci--ppp-dash.elifesciences.org/...` there though and I'm getting elife-dashboard fatigue.

**Comment by lsh-0** [comment]
ok, I've disabled the regular dashboard smoke test, which doesn't actually change anything because it didn't exist before, just to get it passing. It should definitely be revisited once we can safely inject some credentials into it.

**Comment by giorgiosironi** [comment]
Expected unfortunately, but to be revisited :+1:

**Pull request merged**
