### PR TITLE
Feature: dependency bump

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Remember to [manually deploy](https://alfred.elifesciences.org/job/prod-elife-dashboard/).

**Comment by lsh-0** [comment]
> Remember to manually deploy.

I don't this 'dashboard_2' is being used ...

**Comment by lsh-0** [comment]
looks like I'm wrong! 

```
08:35:40 [34.229.120.48] out: ----------
08:35:40 [34.229.120.48] out:           ID: uwsgi-elife-dashboard-2
08:35:40 [34.229.120.48] out:     Function: service.running
08:35:40 [34.229.120.48] out:       Result: True
08:35:40 [34.229.120.48] out:      Comment: The service uwsgi-elife-dashboard-2 is already running
08:35:40 [34.229.120.48] out:      Started: 07:35:38.095740
08:35:40 [34.229.120.48] out:     Duration: 24.773 ms
08:35:40 [34.229.120.48] out:      Changes:   
08:35:40 [34.229.120.48] out: ----------
08:35:40 [34.229.120.48] out:           ID: uwsgi-elife-dashboard-2
08:35:40 [34.229.120.48] out:     Function: cmd.run
08:35:40 [34.229.120.48] out:         Name: service uwsgi-elife-dashboard-2 restart
08:35:40 [34.229.120.48] out:       Result: True
08:35:40 [34.229.120.48] out:      Comment: Command "service uwsgi-elife-dashboard-2 restart" run
08:35:40 [34.229.120.48] out:      Started: 07:35:38.120883
08:35:40 [34.229.120.48] out:     Duration: 1052.827 ms
08:35:40 [34.229.120.48] out:      Changes:   
08:35:40 [34.229.120.48] out:               ----------
08:35:40 [34.229.120.48] out:               pid:
08:35:40 [34.229.120.48] out:                   8049
08:35:40 [34.229.120.48] out:               retcode:
08:35:40 [34.229.120.48] out:                   0
08:35:40 [34.229.120.48] out:               stderr:
08:35:40 [34.229.120.48] out:               stdout:
08:35:40 [34.229.120.48] out:                   uwsgi-elife-dashboard-2 stop/waiting
08:35:40 [34.229.120.48] out:                   uwsgi-elife-dashboard-2 start/running, process 8057
```

I'll have to figure out just what state the article-scheduler+elife-dashboard+elife-dashboard2 are in

**Comment by lsh-0** [comment]
> Remember to manually deploy.

are we talking about pulling the latest version of article scheduler on prod or something else here?

**Comment by giorgiosironi** [comment]
Manual deployment: after https://alfred.elifesciences.org/job/test-elife-dashboard has run, run https://alfred.elifesciences.org/job/prod-elife-dashboard/ to manually deploy as this old project is not pushed to production automatically.

**Comment by giorgiosironi** [comment]
(that will use the `master` of `elife-article-scheduler` too)

**Comment by lsh-0** [comment]
ah, no worries

**Pull request merged**
